# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    # app.storageManager.rootDir: %kernel.root_dir%/data/

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.dataManager:
        class: App\RestBundle\Mock\DataManager
        arguments: [%kernel.cache_dir%, @jms_serializer] # [%app.storageManager.rootDir%]
