parameters:
    serializer.path: "@@AppRestBundle/Resources/serializer"

# FOSRestBundle Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: 'force'
        formats:
            xml: true
            json : true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    routing_loader:
        default_format: json

# JMSSerializerBundle Configuration
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            AppCoreBundle:
                namespace_prefix: "App\\CoreBundle"
                path: "%serializer.path%/AppCoreBundle"

# NelmioApiDocBundle configurations
nelmio_api_doc: ~